### ISSUE TITLE
Function ItemBuilder#glow() isn't available

### ISSUE THREAD

**Issue by DevSnox** [AstrideUG/DarkBedrock#32]
https://github.com/AstrideUG/DarkBedrock/blob/205986e2dd98c2d82148f8da0e59efb6e405e643/Darkness/spigot/src/main/kotlin/net/darkdevelopers/darkbedrock/darkness/spigot/functions/ItemBuilder.kt#L18

**Comment by DevSnox** [comment]
I updated the version to newest and i can find this class but it isn't available.

**Comment by DevSnox** [comment]
@LartyHD

**Comment by LartyHD** [comment]
You must use YourItemBuilder.glow() and 
```kotlin
import net.darkdevelopers.darkbedrock.darkness.spigot.functions.glow
```

**Comment by LartyHD** [comment]
Fixed that your problem?
